valor_og = float(input("Informe o valor da divida: "))
dias_de_atraso = int(input("Quantos dias de atraso: "))
multa = float(input("Juros: "))
valor_atualizado = valor_og + (dias_de_atraso * (multa/100) * valor_og)
print("O valor atualizado da divida é de R$: %.2f" %valor_atualizado)
